# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CovLPCPP <- function(X, p, a, b) {
    .Call('depthproc_CovLPCPP', PACKAGE = 'depthproc', X, p, a, b)
}

depth2dcpp <- function(R_x, R_y) {
    .Call('depthproc_depth2dcpp', PACKAGE = 'depthproc', R_x, R_y)
}

depthMahCPP <- function(ru, rX, rcov, rmean, threads) {
    .Call('depthproc_depthMahCPP', PACKAGE = 'depthproc', ru, rX, rcov, rmean, threads)
}

depthProjCPP <- function(ru, rX, nproj, seed, threads) {
    .Call('depthproc_depthProjCPP', PACKAGE = 'depthproc', ru, rX, nproj, seed, threads)
}

depthLPCPP <- function(ru, rX, p, a, b, threads) {
    .Call('depthproc_depthLPCPP', PACKAGE = 'depthproc', ru, rX, p, a, b, threads)
}

depthTukeyCPP <- function(ru, rX, threads) {
    .Call('depthproc_depthTukeyCPP', PACKAGE = 'depthproc', ru, rX, threads)
}

sampleDepthContForMuCPP <- function(d, mu, rY) {
    .Call('depthproc_sampleDepthContForMuCPP', PACKAGE = 'depthproc', d, mu, rY)
}

sampleMaxDepthForMuCPP <- function(mu, rY, d_min, max_iter, eps) {
    .Call('depthproc_sampleMaxDepthForMuCPP', PACKAGE = 'depthproc', mu, rY, d_min, max_iter, eps)
}

sampleMaxLocScaleDepthCPP <- function(ry, iter, eps, p_length) {
    .Call('depthproc_sampleMaxLocScaleDepthCPP', PACKAGE = 'depthproc', ry, iter, eps, p_length)
}

runifsphereCPP <- function(n, p, seed) {
    .Call('depthproc_runifsphereCPP', PACKAGE = 'depthproc', n, p, seed)
}

covCPP <- function(rX, threads) {
    .Call('depthproc_covCPP', PACKAGE = 'depthproc', rX, threads)
}

meanCPP <- function(rX, threads) {
    .Call('depthproc_meanCPP', PACKAGE = 'depthproc', rX, threads)
}

