# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CovLPCPP <- function(rX, p, a, b) {
    .Call('depthproc_CovLPCPP', PACKAGE = 'depthproc', rX, p, a, b)
}

depth2dcpp <- function(R_x, R_y) {
    .Call('depthproc_depth2dcpp', PACKAGE = 'depthproc', R_x, R_y)
}

depthMahCPP <- function(ru, rX) {
    .Call('depthproc_depthMahCPP', PACKAGE = 'depthproc', ru, rX)
}

runifsphereCPP <- function(n, p) {
    .Call('depthproc_runifsphereCPP', PACKAGE = 'depthproc', n, p)
}

