// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// depth2dcpp
NumericVector depth2dcpp(SEXP R_x, SEXP R_y);
RcppExport SEXP depthproc_depth2dcpp(SEXP R_xSEXP, SEXP R_ySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        SEXP R_x = Rcpp::as<SEXP >(R_xSEXP);
        SEXP R_y = Rcpp::as<SEXP >(R_ySEXP);
        NumericVector __result = depth2dcpp(R_x, R_y);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
